apiVersion: v1
kind: Service
metadata:
  name: {{ include "geotrack.fullname" . }}-api
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "geotrack.fullname" . }}-api
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: geotrack
    helm.sh/chart: {{ include "geotrack.chart" . }}
spec:
  type: {{ .Values.api.service.type | default "ClusterIP" }}
  selector:
    app.kubernetes.io/name: {{ include "geotrack.fullname" . }}-api
  ports:
    - name: http
      port: {{ .Values.api.port }}
      targetPort: http
      protocol: TCP
      {{- if and (eq .Values.api.service.type "NodePort") .Values.api.service.nodePort }}
      nodePort: {{ .Values.api.service.nodePort }}
      {{- end }}
