apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "geotrack.fullname" . }}-api
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "geotrack.fullname" . }}-api
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: geotrack
    helm.sh/chart: {{ include "geotrack.chart" . }}
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "geotrack.fullname" . }}-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "geotrack.fullname" . }}-api
        app.kubernetes.io/component: api
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: geotrack-api
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.api.port }}
              protocol: TCP
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: {{ .Values.config.kafkaBootstrapServers | quote }}
            - name: QUARKUS_DATASOURCE_JDBC_URL
              value: {{ .Values.config.datasourceUrl | quote }}
            - name: QUARKUS_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "geotrack.fullname" . }}-db-credentials
                  key: username
            - name: QUARKUS_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "geotrack.fullname" . }}-db-credentials
                  key: password
          livenessProbe:
            httpGet:
              path: {{ .Values.api.healthCheck.liveness }}
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: {{ .Values.api.healthCheck.readiness }}
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
