{{- if .Values.kafka.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "geotrack.fullname" . }}-kafka
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "geotrack.fullname" . }}-kafka
    app.kubernetes.io/component: messaging
    {{- include "geotrack.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "geotrack.fullname" . }}-kafka
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "geotrack.fullname" . }}-kafka
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "geotrack.fullname" . }}-kafka
        app.kubernetes.io/component: messaging
    spec:
      securityContext:
        fsGroup: 101
      containers:
        - name: redpanda
          image: "{{ .Values.kafka.image.repository }}:{{ .Values.kafka.image.tag }}"
          args:
            - redpanda
            - start
            - --smp=1
            - --memory=512M
            - --reserve-memory=0M
            - --overprovisioned
            - --node-id=0
            - --kafka-addr=internal://0.0.0.0:{{ .Values.kafka.ports.internal }},external://0.0.0.0:{{ .Values.kafka.ports.external }}
            - --advertise-kafka-addr=internal://{{ include "geotrack.fullname" . }}-kafka:{{ .Values.kafka.ports.internal }},external://localhost:{{ .Values.kafka.ports.external }}
          ports:
            - name: kafka
              containerPort: {{ .Values.kafka.ports.internal }}
            - name: kafka-external
              containerPort: {{ .Values.kafka.ports.external }}
            - name: admin
              containerPort: 9644
          livenessProbe:
            httpGet:
              path: /v1/status/ready
              port: admin
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /v1/status/ready
              port: admin
            initialDelaySeconds: 10
            periodSeconds: 5
          resources:
            {{- toYaml .Values.kafka.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/redpanda/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.kafka.storage }}
{{- end }}
