{{- if .Values.kafka.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "geotrack.fullname" . }}-kafka
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "geotrack.fullname" . }}-kafka
    app.kubernetes.io/component: messaging
    {{- include "geotrack.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app.kubernetes.io/name: {{ include "geotrack.fullname" . }}-kafka
  ports:
    - name: kafka
      port: {{ .Values.kafka.ports.internal }}
      targetPort: kafka
    - name: kafka-external
      port: {{ .Values.kafka.ports.external }}
      targetPort: kafka-external
{{- end }}
