{{- if .Values.postgres.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "geotrack.fullname" . }}-postgres
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "geotrack.fullname" . }}-postgres
    app.kubernetes.io/component: database
    {{- include "geotrack.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "geotrack.fullname" . }}-postgres
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "geotrack.fullname" . }}-postgres
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "geotrack.fullname" . }}-postgres
        app.kubernetes.io/component: database
    spec:
      securityContext:
        fsGroup: 999
      containers:
        - name: postgres
          image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}"
          ports:
            - name: postgres
              containerPort: {{ .Values.postgres.port }}
          envFrom:
            - secretRef:
                name: {{ include "geotrack.fullname" . }}-secrets
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "{{ .Values.postgres.credentials.username }}"]
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "{{ .Values.postgres.credentials.username }}"]
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.postgres.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
              subPath: pgdata
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.postgres.storage }}
{{- end }}
