{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "geotrack.fullname" . }}-postgres
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "geotrack.fullname" . }}-postgres
    app.kubernetes.io/component: database
    {{- include "geotrack.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app.kubernetes.io/name: {{ include "geotrack.fullname" . }}-postgres
  ports:
    - name: postgres
      port: {{ .Values.postgres.port }}
      targetPort: postgres
{{- end }}
