apiVersion: v1
kind: Secret
metadata:
  name: {{ include "geotrack.fullname" . }}-secrets
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "geotrack.labels" . | nindent 4 }}
type: Opaque
stringData:
  QUARKUS_DATASOURCE_PASSWORD: {{ .Values.secrets.datasourcePassword | quote }}
  AISSTREAM_API_KEY: {{ .Values.secrets.aisstreamApiKey | quote }}
  POSTGRES_USER: {{ .Values.postgres.credentials.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.credentials.password | quote }}
  POSTGRES_DB: {{ .Values.postgres.credentials.database | quote }}
