{{- if .Values.simulator.ships.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "geotrack.fullname" . }}-simulator-ships
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "geotrack.fullname" . }}-simulator-ships
    app.kubernetes.io/component: simulator
    {{- include "geotrack.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.simulator.ships.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "geotrack.fullname" . }}-simulator-ships
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "geotrack.fullname" . }}-simulator-ships
        app.kubernetes.io/component: simulator
    spec:
      automountServiceAccountToken: false
      containers:
        - name: simulator-ships
          image: "{{ .Values.simulator.image.repository }}:{{ .Values.simulator.image.tag }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          args: ["ships"]
          envFrom:
            - configMapRef:
                name: {{ include "geotrack.fullname" . }}-config
            - secretRef:
                name: {{ include "geotrack.fullname" . }}-secrets
          resources:
            {{- toYaml .Values.simulator.resources | nindent 12 }}
{{- end }}
