apiVersion: v1
kind: Service
metadata:
  name: geotrack-kafka
  namespace: geotrack
  labels:
    app.kubernetes.io/name: geotrack-kafka
    app.kubernetes.io/component: messaging
    app.kubernetes.io/part-of: geotrack
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app.kubernetes.io/name: geotrack-kafka
  ports:
    - name: kafka
      port: 9092
      targetPort: kafka
      protocol: TCP
    - name: kafka-external
      port: 29092
      targetPort: kafka-external
      protocol: TCP
