apiVersion: v1
kind: Service
metadata:
  name: geotrack-processing
  namespace: geotrack
  labels:
    app.kubernetes.io/name: geotrack-processing
    app.kubernetes.io/component: processing
    app.kubernetes.io/part-of: geotrack
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: geotrack-processing
  ports:
    - name: http
      port: 8081
      targetPort: http
      protocol: TCP
