apiVersion: v1
kind: Service
metadata:
  name: geotrack-frontend
  namespace: geotrack
  labels:
    app.kubernetes.io/name: geotrack-frontend
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: geotrack
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: geotrack-frontend
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
