apiVersion: v1
kind: Service
metadata:
  name: geotrack-postgres
  namespace: geotrack
  labels:
    app.kubernetes.io/name: geotrack-postgres
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: geotrack
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app.kubernetes.io/name: geotrack-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
      protocol: TCP
