apiVersion: v1
kind: Service
metadata:
  name: geotrack-sonarqube
  namespace: geotrack
  labels:
    app.kubernetes.io/component: sonarqube
spec:
  type: NodePort
  ports:
    - port: 9000
      targetPort: http
      nodePort: 30900
      name: http
  selector:
    app.kubernetes.io/component: sonarqube
