apiVersion: v1
kind: Service
metadata:
  name: geotrack-api
  namespace: geotrack
  labels:
    app.kubernetes.io/name: geotrack-api
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: geotrack
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: geotrack-api
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
