apiVersion: v1
kind: ConfigMap
metadata:
  name: geotrack-config
  namespace: geotrack
  labels:
    app.kubernetes.io/part-of: geotrack
data:
  QUARKUS_DATASOURCE_JDBC_URL: "jdbc:postgresql://geotrack-postgres:5432/geotrack"
  QUARKUS_DATASOURCE_USERNAME: "geotrack"
  QUARKUS_DATASOURCE_DB_KIND: "postgresql"
  KAFKA_BOOTSTRAP_SERVERS: "geotrack-kafka:9092"
  OPENSKY_ENABLED: "true"
  AISSTREAM_ENABLED: "true"
  QUARKUS_HTTP_PORT: "8080"
  QUARKUS_REDIS_HOSTS: "redis://geotrack-redis:6379"
  JAVA_OPTS: "-XX:+UseG1GC -XX:MaxRAMPercentage=75.0"
