apiVersion: v1
kind: ConfigMap
metadata:
  name: geotrack-config
  namespace: geotrack
  labels:
    app.kubernetes.io/part-of: geotrack
data:
  KAFKA_BOOTSTRAP_SERVERS: "geotrack-kafka-0.geotrack-kafka.geotrack.svc.cluster.local:9092"
  QUARKUS_DATASOURCE_JDBC_URL: "jdbc:postgresql://geotrack-postgres.geotrack.svc.cluster.local:5432/geotrack"
  QUARKUS_DATASOURCE_DB_KIND: "postgresql"
  QUARKUS_HTTP_PORT: "8080"
  JAVA_OPTS: "-XX:+UseG1GC -XX:MaxRAMPercentage=75.0"
