apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: geotrack

commonLabels:
  app.kubernetes.io/part-of: geotrack
  app.kubernetes.io/managed-by: kustomize

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - api-service/deployment.yaml
  - api-service/service.yaml
  - api-service/hpa.yaml
  - processing-service/deployment.yaml
  - processing-service/service.yaml
  - frontend/deployment.yaml
  - frontend/service.yaml
  - simulator/deployment-live.yaml
  - simulator/deployment-ships.yaml
  - postgres/statefulset.yaml
  - postgres/service.yaml
  - kafka/statefulset.yaml
  - kafka/service.yaml
