apiVersion: v1
kind: Secret
metadata:
  name: geotrack-db-credentials
  namespace: geotrack
  labels:
    app.kubernetes.io/part-of: geotrack
type: Opaque
data:
  # base64 encoded placeholder values â€” replace in overlays or sealed-secrets
  QUARKUS_DATASOURCE_USERNAME: Z2VvdHJhY2s=        # geotrack
  QUARKUS_DATASOURCE_PASSWORD: Y2hhbmdlbWU=          # changeme
  POSTGRES_USER: Z2VvdHJhY2s=                        # geotrack
  POSTGRES_PASSWORD: Y2hhbmdlbWU=                     # changeme
  POSTGRES_DB: Z2VvdHJhY2s=                           # geotrack
