name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build & Test
        run: mvn verify -B

      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: geotrack-frontend/package-lock.json

      - name: Frontend Build
        working-directory: geotrack-frontend
        run: |
          npm ci
          npx ng build --configuration=production

      - name: Upload API artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: geotrack-api
          path: geotrack-api/target/quarkus-app/

      - name: Upload Processing artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: geotrack-processing
          path: geotrack-processing/target/quarkus-app/

      - name: Upload Frontend artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: geotrack-frontend
          path: geotrack-frontend/dist/
